-- MySQL Script generated by MySQL Workbench
-- Wed Sep 30 15:22:30 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackathon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackathon` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hackathon` ;

-- -----------------------------------------------------
-- Table `hackathon`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`user` (
  `ID` INT(11) NOT NULL COMMENT '',
  `first` VARCHAR(55) NOT NULL COMMENT '',
  `last` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(255) NULL COMMENT '',
  `password` VARCHAR(32) NOT NULL COMMENT '',
  `phone` INT(12) NULL COMMENT '',
  `account_type` INT NULL COMMENT '',
  PRIMARY KEY (`ID`)  );


-- -----------------------------------------------------
-- Table `hackathon`.`loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`loan` (
  `ID` INT NOT NULL COMMENT '',
  `title` VARCHAR(45) NULL COMMENT '',
  `amount` DECIMAL(10,2) NULL COMMENT '',
  `intrest` FLOAT NULL COMMENT '',
  `term` INT(11) NULL COMMENT '',
  `start` DATETIME NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `balance` DECIMAL(10,2) NULL COMMENT '',
  `status` INT NULL COMMENT '',
  PRIMARY KEY (`ID`)  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hackathon`.`user_loan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hackathon`.`user_loan` (
  `ID` INT NOT NULL COMMENT '',
  `user_ID` INT(11) NOT NULL COMMENT '',
  `loan_ID` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  ,
  INDEX `fk_user_loan_user_idx` (`user_ID` ASC)  ,
  INDEX `fk_user_loan_loan1_idx` (`loan_ID` ASC)  ,
  CONSTRAINT `fk_user_loan_user`
    FOREIGN KEY (`user_ID`)
    REFERENCES `hackathon`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_loan_loan1`
    FOREIGN KEY (`loan_ID`)
    REFERENCES `hackathon`.`loan` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
